---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
<% %w(12.14 12.7 12.1).each do |chef_version| %>
  - name: ubuntu-14.04-chef<%= chef_version %>
    driver_config:
      image: ubuntu:14.04
      platform: ubuntu
      require_chef_omnibus: <%= chef_version %>
      provision_command:
          - apt-get install net-tools -y
  - name: ubuntu-15.10-chef<%= chef_version %>
    driver_config:
      box: ubuntu:15.10
      platform: ubuntu
      run_command: /sbin/init
      privileged: true
      provision_command:
        - apt-get install net-tools -y
    provisioner:
      require_chef_omnibus: <%= chef_version %>
  - name: debian-8.5-chef<%= chef_version %>
    driver_config:
      box: debian:8.5
      platform: debian
      run_command: /sbin/init
      privileged: true
      provision_command:
        - apt-get install wget -y
        - apt-get install net-tools -y
    provisioner:
      require_chef_omnibus: <%= chef_version %>
  - name: centos-6.8-chef<%= chef_version %>
    driver_config:
      box: centos:6.8
      platform: centos
      provision_command:
       - yum install net-tools -y
       - yum install iproute -y
    provisioner:
      require_chef_omnibus: <%= chef_version %>
  - name: centos-7.2-chef<%= chef_version %>
    driver_config:
      box: centos:7.2
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - yum install net-tools -y
        - yum install iproute -y
    provisioner:
      require_chef_omnibus: <%= chef_version %>
<% end %>

suites:
  - name: default
    run_list:
      - recipe[influxdb-test::default]
      - recipe[netstat]
    attributes:
  - name: file
    run_list:
      - recipe[influxdb-test::default]
    attributes:
      influxdb:
        install_type: file
        shasums:
          debian: 88f6c30fec2c6e612e802e23b9161fdfc7c5c29f6be036f0376326445aff0037
          rhel: 5efa2e4060e75a07ad1a3abd094322c708131c73be575e0ffe41817b788ff44a
  - name: config_change
    run_list:
      - recipe[influxdb-test::default]
      - recipe[influxdb-test::config_change]
